from sqlalchemy import Column, Integer, String, Float, Boolean, ForeignKey, DateTime
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.core.database import Base


class Goal(Base):
    __tablename__ = "goals"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    title = Column(String, nullable=False)
    description = Column(String, nullable=True)

    # Frequency: "daily", "weekly", "monthly", "long_term"
    frequency = Column(String, default="weekly")
    category = Column(String, default="learning")  # "health", "learning", "work", "personal"
    metric = Column(String, default="hours")  # "steps", "hours", "calories", "kg", "tasks"

    target_value = Column(Float, nullable=False)
    current_value = Column(Float, default=0.0)
    start_date = Column(String, nullable=True)
    deadline = Column(String, nullable=True)
    is_completed = Column(Boolean, default=False)

    user = relationship("User", back_populates="goals")


class Challenge(Base):
    """
    Challenges (e.g. 15-day step challenge, 30-hour Python challenge).
    """
    __tablename__ = "challenges"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    title = Column(String, nullable=False)
    description = Column(String, nullable=True)
    duration_days = Column(Integer, default=15)
    target_metric = Column(String, nullable=False)  # "steps_daily", "hours_total", "dsa_questions"
    target_value_per_day = Column(Float, nullable=True)
    total_target_value = Column(Float, nullable=True)

    days_completed = Column(Integer, default=0)
    current_progress = Column(Float, default=0.0)
    start_date = Column(String, nullable=False)
    end_date = Column(String, nullable=False)
    is_active = Column(Boolean, default=True)
    is_successful = Column(Boolean, default=False)

    user = relationship("User", back_populates="challenges")


class DailySummary(Base):
    """
    Deterministic calculated daily statistics + optional AI insights.
    """
    __tablename__ = "daily_summaries"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    date = Column(String, nullable=False, index=True)  # "YYYY-MM-DD"

    total_available_time_minutes = Column(Integer, default=0)
    total_required_time_minutes = Column(Integer, default=0)
    focus_time_minutes = Column(Integer, default=0)
    steps = Column(Integer, default=0)
    calories_consumed = Column(Float, default=0.0)
    tasks_completed = Column(Integer, default=0)
    tasks_total = Column(Integer, default=0)
    overall_progress_pct = Column(Float, default=0.0)

    # Narrative insights generated by AI or rule engine
    morning_brief = Column(String, nullable=True)
    evening_checkin = Column(String, nullable=True)
    night_review = Column(String, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", back_populates="daily_summaries")
